### PR TITLE
use pubmed search arg resulType=core and use richer attributes

### LINKED ISSUE #1153: Abstract of Pubmed is not included (also does not work in prod)

### PR DESCRIPTION
**Pull request by nicolasfranck**
Fixes #1153 , and adds other attributes from pubmed api, using the more rich api:

* add abstract. Language is always set to `eng`. ok?
* uses array `authorList.author` which holds an array of objects, instead of trying to parse `authorString`. Advantage is that `firstName` and `lastName` can now be extracted in full, while previously it showed `<first-name> <abbreviation-of-last-name`. e.g. `Gonzalez N`
* retrieve full journal title instead of abbreviation (`Plant physiology` instead of `Plant Physiol`)
* add language (different from language of abstract?)

### CODE REVIEW

File: internal/backends/pubmed/client.go [hunk 1]
```diff
@@ -13,6 +13,23 @@ import (
 	"github.com/ugent-library/biblio-backoffice/internal/models"
 )
 
+// api reference: https://europepmc.org/RestfulWebService
+/*
```
Comment (nics) [inline internal/backends/pubmed/client.go:17]: thisis not needed

File: internal/backends/pubmed/client.go [hunk 2]
```diff
@@ -78,23 +96,38 @@ func (c *Client) GetPublication(id string) (*models.Publication, error) {
...
 		p.Year = res.String()
 	}
-	if res := attrs.Get("authorString"); res.Exists() {
-		for _, r := range reSplit.Split(res.String(), -1) {
-			nameParts := strings.Split(strings.ReplaceAll(r, ".", ""), " ")
-			firstName := nameParts[len(nameParts)-1]
-			lastName := strings.Join(nameParts[:len(nameParts)-1], " ")
+	if authorList := attrs.Get("authorList.author"); authorList.IsArray() {
+		for _, author := range authorList.Array() {
+			var firstName string
```
Comment (nics) [inline internal/backends/pubmed/client.go:123]: `firstName := author.Get("firstName").String()`

I think the other importers also add `[missing]` if a name part is empty (see crossref importer)

Comment (nicolasfranck) [reply internal/backends/pubmed/client.go]: done

**Review by nics — APPROVED** [review]
