### PR TITLE
Fix issue 1058

### LINKED ISSUE #1058: [Rogue] Remove time field from publication forms, keep information around.
# Improvement

Remove time field from publication forms, keep information around.

For dissertations, we ask for the **Time of defense**:
Scherm­afbeelding 2023-04-11 om 13 50 55
Scherm­afbeelding 2023-04-11 om 14 08 28

When I asked around who uses this information; nobody could answer me.
People often do not know when it happened or fail to find that information, and since it is a required field people just fill out _something_.

Example: https://backoffice.biblio.ugent.be/publication/01GX7YWD4DCT65Q80Z23761P66?redirect-url=%2Fpublication%3Fq%3D%26f%255Btype%255D%3Ddissertation

### When this ticket is done

- [ ] Nobody needs fill out this field – it is not required any longer.
- [ ] Nobody needs to see this field.
- [ ] The historic information is kept around, but it is hidden.
- [ ] [TBD] we keep the infrastructure around for one year, if nobody complains, we throw it all out.
- [x] The information is not shown in our front-office.

Please comment if I did not foresee specific problems.

### Next year

- If nobody complained before 01/04/2024, we remove this joke completely.

## Who to blame if anyone asks

Send them to @mietcls

### PR DESCRIPTION
**Pull request by nicolasfranck**
fixes #1058 

What it does:

* removes publication field `defense_time` from the views and validation
* no longer appends `defense_time` to frontend publication field `defense.date` (resulting in `<date> <time>` in that field)

Requires reindexation of the frontend publications. Just simply ignoring the time field part in the frontend field `defense.date` was also an option, but that "fix" had to be applied on several places, and introduces "changes" to the oai data anyway.

Not urgent

### CODE REVIEW

File: internal/app/displays/dissertation_details.go [hunk 1]
```diff
@@ -84,11 +84,13 @@ func dissertationDetails(user *models.User, l *locale.Locale, p *models.Publicat
 				Value:    p.DefenseDate,
 				Required: p.ShowDefenseAsRequired(),
 			},
-			&display.Text{
-				Label:    l.T("builder.defense_time"),
-				Value:    p.DefenseTime,
-				Required: p.ShowDefenseAsRequired(),
-			},
+			// https://github.com/ugent-library/biblio-backoffice/issues/1058
```
Comment (nics) [inline internal/app/displays/dissertation_details.go:87]: this really pollutes the code, just delete the lines

**Review by nics — CHANGES_REQUESTED** [review]

**Review by nics — COMMENTED** [review]
@nicolasfranck better to mark the model struct field as deprecated

**Review by nics — APPROVED** [review]
