### PR TITLE
fix issue #1503: Refactor to templ: dataset tab "People & affiliations / Contributors"

### LINKED ISSUE #1503: Refactor to templ: dataset tab "People & affiliations / Contributors"

### PR DESCRIPTION
**Pull request by nicolasfranck**
fixes #1503

### CODE REVIEW

File: routes/register.go [hunk 1]
```diff
@@ -395,6 +395,7 @@ func Register(c Config) {
 					r.Use(ctx.RequireViewDataset)
 
 					// view only functions
+					r.With(ctx.SetNav("datasets"), ctx.SetSubNav("contributors")).Get("/contributors", datasetviewing.ShowContributors).Name("dataset_contributors")
```
Comment (nics) [inline routes/register.go:398]: SetNav not needed, already set higher up

**Review by nics — CHANGES_REQUESTED** [review]

File: routes/register.go (hunk 1 above)
Comment (nicolasfranck) [reply routes/register.go:398]: Ah where?
