### PR TITLE
fix issue 1375

### LINKED ISSUE #1375: Show clickable urls and newlines in reviewer comments
# Enhancement

Comments that are entered by reviewers in the publication/dataset tab `Biblio messages`
are shown in the list of datasets/publications. These comments often contain url's and
newlines. 

Right now these urls are shown as they are (i.e. plain text), and therefore require an extra
copy and paste to visit them.

Also newlines have no meaning in html, so are made useless.

## Expected behavior
In order to make the visualisation better:

* convert every url in the plain text block into a clickable url. Important: make sure that url's on the end of a line, or within brackets for example are also recognized.
* convert every newline into an `<br>`

### PR DESCRIPTION
**Pull request by nicolasfranck**
fixes #1375 

how:

* added new func `renderMsg` to template funcmap that receives (unsafe) string and returns html safe string (template.HTML). Implemented as a filter.
* `renderMsg` does the following:
  * html escape input
  * replace newlines by `<br>`
  * replace all https links by `<a>`. Extracting urls was not trivial, as in all of the examples, the urls where hardly ever put between spaces, but mostly between parenthesises, before a dot, after a colon.. So I could not use something like "what is parseable as an url", as that required word extraction first. The limitation on https is due to the library that either allows for matching on a whole set of [schemes](https://pkg.go.dev/mvdan.cc/xurls/v2#Strict) (from http to file, which to much), or either one [scheme](https://pkg.go.dev/mvdan.cc/xurls/v2#StrictMatchingScheme). I think https is enough? Didn't feel the urge to search any further.

### CODE REVIEW

File: urls/funcmap.go [hunk 1]
```diff
@@ -86,3 +90,38 @@ func queryClear(u *url.URL) (*url.URL, error) {
...
+		// NON URL
+		prefix := oldVal[startPos:pair[0]]
+		if len(prefix) > 0 {
+			newValBuilder.WriteString(prefix)
+		}
+
+		//URL
+		postfix := oldVal[pair[0]:pair[1]]
+		newValBuilder.WriteString("<a href=\"")
+		newValBuilder.WriteString(html.EscapeString(postfix))
```
Comment (nics) [inline urls/funcmap.go:115]: Why is this double escaped?

File: urls/funcmap.go [hunk 2]
```diff
@@ -86,3 +90,38 @@ func queryClear(u *url.URL) (*url.URL, error) {
 
 	return &newU, nil
 }
+
+func renderMsg(oldVal string) template.HTML {
+	oldVal = html.EscapeString(oldVal)
+
+	oldVal = strings.ReplaceAll(oldVal, "\r\n", "\n")
```
Comment (nics) [inline urls/funcmap.go:97]: Why is this necessary?

File: urls/funcmap.go [hunk 3]
```diff
@@ -86,3 +90,38 @@ func queryClear(u *url.URL) (*url.URL, error) {
...
+	oldVal = strings.ReplaceAll(oldVal, "\n", "<br>")
```
Comment (nics) [inline urls/funcmap.go:98]: Why is this necessary?

File: urls/funcmap.go (hunk 2 above)
Comment (nicolasfranck) [reply urls/funcmap.go:97]: I'm just not sure that all newlines are windows/internet newlines (where `\r\n` is used). Better safe than sorry?
